[package]
name = "anchor-spl"
version = "0.11.0"
authors = ["Serum Foundation <foundation@projectserum.com>"]
edition = "2018"
license = "Apache-2.0"
description = "CPI clients for SPL programs"

[features]
devnet = []

[dependencies]
anchor-lang = { path = "../lang", version = "0.11.0", features = ["derive"] }
lazy_static = "1.4.0"
serum_dex = { path = "../../prediction_market/deps/serum-dex/dex", features = ["no-entrypoint"] }
solana-program = "1.7.4"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
